name: GocCandidature
main: fr.yopaman.goccandid.GocCandid
version: 0.0.1
description: Plugin de candidature pour le serveur Gloireocube
author: Yopaman
commands:
  candidature:
    description: Commande de candidature, seule commande du plugin
    usage: §4Erreur de syntaxe avec la commande.
    permission: goccandid.candidature
permissions:
  goccandid.candidature:
    description: Permet d'utiliser la commande de candidature
    default: false
  goccandid.candidature.listnew:
    description: Permet d'utiliser la commande pour lister les candidatures non acceptées.
    default: false
  goccandid.candidature.get:
    description: Permet d'utiliser la commande pour obtenir une candidature en particulier.
    default: false
  goccandid.candidature.accept:
    description: Permet d'utiliser la commande pour accepter une candidature.
    default: false
  goccandid.candidature.refuse:
    description: Permet d'utilisser la commande pour refuser une candidature.
  goccandid.staff:
    description: Permet de recevoir les notifications quand un joueur fait sa candidature + quand il y a des candidatures non acceptées.
    default: false
